import sharp from 'sharp';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeFileSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const iconsDir = join(__dirname, '../src-tauri/icons');
const svgPath = join(iconsDir, 'icon.svg');

async function generateIco() {
  console.log('Generating Windows icon files...');
  
  // For Windows, we'll generate PNG files in multiple sizes
  // Tauri will bundle them properly
  const sizes = [16, 24, 32, 48, 64, 128, 256];
  
  try {
    // Generate all PNG sizes
    for (const size of sizes) {
      await sharp(svgPath)
        .resize(size, size, {
          fit: 'contain',
          background: { r: 255, g: 255, b: 255, alpha: 0 }
        })
        .png()
        .toFile(join(iconsDir, `${size}x${size}.png`));
      console.log(`✓ Generated ${size}x${size}.png`);
    }
    
    // Create a simple 256x256 icon.png as fallback
    await sharp(svgPath)
      .resize(256, 256, {
        fit: 'contain',
        background: { r: 255, g: 255, b: 255, alpha: 0 }
      })
      .png()
      .toFile(join(iconsDir, 'icon.png'));
    console.log('✓ Generated icon.png (256x256)');
    
    console.log('\nNote: icon.ico will be generated by Tauri during build');
  } catch (error) {
    console.error('✗ Failed to generate icon files:', error.message);
  }
}

generateIco().catch(console.error);
